F/amqp rework
SAREhub/PHP_Client pull request #36
Opened 2017-11-02 08:36 UTC by Mararok

2017-11-02 10:16 UTC, kuba9392 commented on src/SAREhub/Client/Amqp/BasicAmqpProcessConfirmStrategy.php
> +    public function confirm(AmqpChannelWrapper $channel, Message $orginalIn, Exchange $exchange)
little typo in $orginalIn variable, should be $originalIn.

2017-11-02 10:16 UTC, kuba9392 commented on tests/unit/SAREhub/Client/Amqp/AmqpChannelWrapperTest.php
> +        //$this->channel->allows(["basic_consume" => $this->consumer->getOptions()->getTag()]);
if this is unused then comment should be deleted

2017-11-02 10:16 UTC, kuba9392 commented on tests/unit/SAREhub/Client/Processor/PipelineTest.php
>          $this->pipeline
are there any assertions?

2017-11-02 10:59 UTC, Mararok commented on tests/unit/SAREhub/Client/Processor/PipelineTest.php
>          $this->pipeline
yes look at all file

2017-11-02 11:10 UTC, kuba9392 requested changes
waiting for changes described in comments

2017-11-07 09:16 UTC, kuba9392 approved these changes

2017-11-07 09:18 UTC, merged